---
include:
  - board: nice_nano
    shield: kb_left
  - board: nice_nano
    shield: kb_right
  - board: nice_nano
    shield: kb_dongle
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano
    shield: cradio_left
  - board: nice_nano
    shield: cradio_right
