manifest:
  remotes:
    - name: dusanlesan
      url-base: https://github.com/DusanLesan
  projects:
    - name: zmk
      remote: dusanlesan
      revision: feat/power-idle-sleep-while-ble-connected
      import: app/west.yml
  self:
    path: config
