manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/newx-it
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat-ble-prevent-sleep-feat-usb-allow-sleep
      import: app/west.yml
  self:
    path: config
