file_format: "1"
id: kyria_rev3
name: Kyria Rev3
type: shield
url: https://splitkb.com/products/kyria-pcb-kit
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - kb_left
  - kb_right
  - kb_dongle
